### PR TITLE
Add tests to CUDA CI

### PR DESCRIPTION
**Pull request by eidenyoshida**

### CODE REVIEW

**Review by ntrost57 — APPROVED** [review]

**Comment by eidenyoshida** [comment]
Looks to be some test errors. Wondering if anyone on rocsparse team can have a look at them?

**Comment by YvanMokwinski** [comment]
> Looks to be some test errors. Wondering if anyone on rocsparse team can have a look at them?

It's on our list :)  I will keep you updated

**Comment by jsandham** [comment]
Turned CI back on to see if we have all failures fixed

**Review by jsandham — APPROVED** [review]

**Comment by eidenyoshida** [comment]
Jenkins automatically merges develop branch into PR branch when running CI

**Pull request merged**
