### PR TITLE
enum change to match cusparse

### PR DESCRIPTION
**Pull request by ntrost57**
Match cusparse

### CODE REVIEW

**Review by YvanMokwinski — APPROVED** [review]
I don't understand what kind of match is needed here, in other words why do we have to rename HIPSPARSE_ORDER_COLUMN to _COL because of CUSPARSE_ORDER_COL.

**Comment by ntrost57** [comment]
To match cusparse. We are supposed to have identical API for portability.

**Comment by ntrost57** [comment]
Should hold this one back for next major release tho

**Review by jsandham — APPROVED** [review]

**Comment by ntrost57** [comment]
I have changed HIPSPARSE_ORDER_COLUMN to be deprecated instead of being removed.

**Pull request merged**
